version: '3.8'

x-common-variables: &common-variables
  NODE_ENV : development
  JWT_SECRET : abc123
  MONGO_URI : "${MONGO_URI}"
  # enabling this flag because of host header checking
  DANGEROUSLY_DISABLE_HOST_CHECK: true

services:
  backend:
    build:
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./backend:/app/backend
    environment:
      <<: *common-variables
      PORT: 3000

  frontend:
    build:
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    environment:
      <<: *common-variables
      PORT: 3000
  
  nginx:
    depends_on:
      - backend
      - frontend
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - 3000:80